### ISSUE TITLE
Main form has button exit partially hidden.

### ISSUE THREAD

**Issue by fredvs** [galaxysite/gorg64#1]
Hello.

On my system, the button exit is partially masked.
Also, but it is question of taste, I prefer to have a line border for the main form, mainly when the background is also white.

![gorg64_main](https://github.com/user-attachments/assets/25a0bc76-f99b-4496-a426-eab73dafd2af)

In case you like it, in attachment the units.

[GORG64_main.zip](https://github.com/user-attachments/files/17651996/GORG64_main.zip)

**Comment by galaxysite** [comment]
I upload to Git repository shorted (only Pascal) version without full-installation programs. With [given ](https://github.com/user-attachments/files/17651996/GORG64_main.zip).

**Comment by fredvs** [comment]
Great!
Please add a readme.md with description of your project.
And with screenshots in the readme.md of all the feature is even better!
And maybe transfer all the source in /src/ directory and only let readme.md, copyright.txt, install.txt in the root directory of project.

**Comment by fredvs** [comment]
Added in attachment **georg64.prj** with more "universal" config (not with your directories but from the mseide macros).
[gorg64.prj.zip](https://github.com/user-attachments/files/17667835/gorg64.prj.zip)

**Comment by galaxysite** [comment]
Thank You, Fred !
I upload .prj. 

I'll also think about the readme, screenshots and reorganization.

**Comment by fredvs** [comment]
Maybe, to stay in the mood, the same could be done for inputbox form.

![georg64_input](https://github.com/user-attachments/assets/d3c01d85-6017-4e7b-a765-60ec69698bf7)

Here the source if you like it:
...

[EDIT] Ooops, [&] char was not perfect, sorry, here the updated zip:
[gorg64-inputbox.zip](https://github.com/user-attachments/files/17668448/gorg64-inputbox.zip)

**Comment by galaxysite** [comment]
Thank You ! The design has become more attractive. In the future, internationalization can be added.

**Comment by fredvs** [comment]
On my screen 1388 x 748 the tpopupmenu of main form is too big.
What do you think to use icons 32x32 in place of the 64x64 ?
If you like it I can do a pull-request.

![popup_shot](https://github.com/user-attachments/assets/dcdce797-d01e-44de-842e-d888fa81416d)

**Comment by galaxysite** [comment]
> If you like it I can do a pull-request.
Ok. Let's do that.

**Comment by fredvs** [comment]
OK, perfect!

I will also add fr_FR.txt and es_ES.txt.
It works great!

A proposition: 
My computer is configured for locale **en_US** because for installing things it is more easy.
But I use a Spanish keyboard and I have set Spanish language for my favorite apps.
When loading GORG64, it loads then logically the English language.
It would be nice if in settings I may choose what language to use for next loading.
But this is for later of course!

**Comment by fredvs** [comment]
Wow, your last commit with language select in Settings works great!

I have transferred the language button from about tab to main panel tab.
