### ISSUE TITLE
About sound, script, language and last pull-request.

### ISSUE THREAD

**Issue by fredvs** [galaxysite/gorg64#13]
I was fighting to make sound and script work but I fail.
So I have done the "GORG64-OOTB" version like explained before.
This to have all the needed files in the sub-directory of gorg64 binary.

To compile that version, just add the "-dootb" (and "-B" of course) fpc parameter (to define ootb).
Also, the sub-directory are created and must be filled:
   ./music  
   ./sound
   ./script
   ./lang_s
   ./flash
   ./bin   ---> with all the gorg64_* applications.
   ./data  ---> for tun.bin, gorg.txt, +_commandline.txt

And now the surprise: using that version of gorg64-ootb makes the sound (via Mplayer only) and the script work!

I am still investigate why that way it works but not with the "deb" way.

Other thing, about language.
I have set the list of language based on the files disposable in /lang_s directory.
Also, for DetectLang(), the 2 first characters of GetEnvironmentVariable('LANG') are used.
This because, imho, the particularity of each country is not needed and stops to use a language if not the "default" country.

Last change: all the lang files are renamed:
   lang_s/ru_RU.txt -> lang_s/ru_Russian.txt
   lang_s/en_US.txt -> lang_s/en_English.txt
   lang_s/es_ES.txt -> lang_s/es_Spanish.txt
   lang_s/fr_FR.txt -> lang_s/fr_French.txt

Voila, for me gorg64 is wow now and I use it.

[EDIT] Oooops, there is one exception for using 2 first chars: **syr_SY**.  OK, I will asap update the code using **pos**('_',str).

**Comment by fredvs** [comment]
Ho, you did accept the pull-request to fast, I wanted to delete it.
Running the gorg64-ootb works great but now if I try the "deb" version, the events are not loaded.

It is late and I dont have the energy to continue the combat tonight.
Sorry for that.

**Comment by fredvs** [comment]
Ooops, no, it is ok with the "deb" version, I had set to "disable action".
Just the sound and script does not work on "deb" version but that was also before last commit.
I have to stop now, sorry.
Write you later...

**Comment by fredvs** [comment]
The last before I fall asleep.
All is ok with the "deb" version, sound too and script too.

But there is a problem with "disable action".
The main panel was not yellow and so I did not know it was disabled.
Sadly I cannot reproduce it but yes, it has happened and will fight for that asap.

Good night and perfect day.

**Comment by fredvs** [comment]
The very, very last.

I think that maybe the problem is there:

```
procedure tmainfo.DisplayMuteNoact;
begin
if tun.p^.fmute then begin
  mainfo.tpopupmenu1.menu.items[0].caption := '[v] ' + str_mute;
  mainfo.tpaintbox1.color := cl_yellow;
   end else begin mainfo.tpopupmenu1.menu.items[0].caption := str_mute;
     mainfo.tpaintbox1.color := cl_white;
   end;
if tun.p^.fnoact then  // and what about the mainfo.tpaintbox1 yellow color?
  mainfo.tpopupmenu1.menu.items[1].caption := '[v] ' + str_noact
  else mainfo.tpopupmenu1.menu.items[1].caption := str_noact;

invalidatewidget;
end;
```

If only "disable action" is enabled, no yellow color.

**Comment by fredvs** [comment]
Just from my dreams.

Maybe use a more universal-elegant way for the name of language files.
Use the name used by the language and a custom extension like .gla or something else. 

ru_русский.gla
fr_Français.gla
sp_español.gla
en_English.gla

...

I go back to sleep.

**Comment by fredvs** [comment]
Good morning!

About the yellow main form problem.
What do you think to have 2 paintbox with 1/2 of height of the form?
If not muted and not disable action, all is white.
If only sound is muted, top paintbox is yellow and bottom is white.
If only action is disabled, the bottom paintbox is yellow and top is white.
If action is disabled and sound muted, all is yellow.


![mainform2](https://github.com/user-attachments/assets/9b52a29e-5dbf-46b0-af17-ab0c400dcedc)


?

**Comment by galaxysite** [comment]
This is an interesting solution, I like it.

**Comment by fredvs** [comment]
OK, it's sold!
