### ISSUE TITLE
deb from release dont run on older Linux system.

### ISSUE THREAD

**Issue by fredvs** [galaxysite/gorg64#36]
I did install **gorg64** with the **deb** file from https://github.com/galaxysite/gorg64/releases on a Debian 11 bullseye machine.
Sadly there is that error when running **gorg64**:

```
$ gorg64
gorg64: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34 not found.

```

This is because **gorg64** in the deb file was compiled on a system with last libc.so.6 using last **GLIBC_2.34** symbol table, that is not present on my system.
With official fpc, because no signed symbol table was assigned to any of the libc methods, the linker take the responsibility to do the job and assign a signed symbol table for the "nude" methods and choose the last installed on the system (that maybe soon could not be compatible with fpc who use the definitions of **GLIBC_2.2.5** table) .

If you prefer to give as release a **deb** file that old , present and future distros can run, maybe you could compile **gorg64** and all the other binaries using **fpc-ootb** who assigns the **GLIBC_2.2.5** table used since the beginning of fpc and create a deb-for-release using those binaries.

Or compile it on a older Linux system that still use **GLIBC_2.2.5** using official fpc.

My 0,001 cent, of course.

**Comment by galaxysite** [comment]
I have done make ootb .deb and compile gorg with it.

And put result to release as  gorg64_2.0.0-2_amd64.deb  and rewrite .rpm.

**Comment by galaxysite** [comment]
http://soft.self-made-free.ru/fpcootb_7.tar.xz
http://soft.self-made-free.ru/fpcootb_3.2.4-1_amd64.deb

**Comment by galaxysite** [comment]
And may be need to upgrade bullseye to bookworm:

https://www.debian.org/releases/bullseye/ :
Debian 11 has been superseded by Debian 12 ("bookworm").

I use sid :)

**Comment by fredvs** [comment]
>And may be need to upgrade bullseye to bookworm:

Yes but for the users that dont want to upgrade....

I will test your last release asap on bullseye, write you later.

**Comment by fredvs** [comment]
I did try to install the new release https://github.com/galaxysite/gorg64/releases/download/rel1/gorg64_2.0.0-2_amd64.deb

It install ok but when trying to run it:
```
$ gorg64
gorg64: symbol lookup error: gorg64: undefined symbol: sem_destroy, version GLIBC_2.2.5
```

**Comment by fredvs** [comment]
Here the deb file working on bullseye, compiled with fpc-ootb 3.2.4:

[gorg64_2.0.0-2_amd64.deb.zip](https://github.com/user-attachments/files/17966247/gorg64_2.0.0-2_amd64.deb.zip)

And here the Makefile used:

[Makefile.zip](https://github.com/user-attachments/files/17966253/Makefile.zip)

**Comment by galaxysite** [comment]
unzip gorg64_2.0.0-2_amd64.deb.zip 
Archive:  gorg64_2.0.0-2_amd64.deb.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

**Comment by galaxysite** [comment]
:) this is tar archive.

**Comment by fredvs** [comment]
Ooops, indeed, I used **tar**.
Do you need zip?

**Comment by fredvs** [comment]
The problem is that github does not accept *.deb files as attachment.
So I did a compressed with zip extension accepted by github.
Maybe just change the .zip with .tar.
If it does not work, I will do the compression using zip.

**Comment by galaxysite** [comment]
I upgrade release. untar is Ok.

**Comment by fredvs** [comment]
> http://soft.self-made-free.ru/fpcootb_7.tar.xz http://soft.self-made-free.ru/fpcootb_3.2.4-1_amd64.deb

Nice but...
When the compilation of fpc-ootb is done and installed in a temp directory, there must be some more work because fpc-ootb architecture of directory is not the same as fpc.

In the root directory of fpc-ootb:

**fpc-ootb** (the renamed binary of updated ppcx64, this because devs of fpc ask me to not use the same name)
**fpide-ootb** (the fp-ide binary renamed.)
**fpc.cfg** (updated fpc.cfg for fpc-ootb)

and those directories:
**/units**  (the directory with all the units)
**/tools** (the directory with all binaries like **fpres**, ...)

You may check in the release fpc-ootb how it is done.

**Comment by fredvs** [comment]
Ok, with last deb in github release it is ok in older Linux distros.
