### ISSUE TITLE
The captions in tpopupmenu1 from main form are not visible.

### ISSUE THREAD

**Issue by fredvs** [galaxysite/gorg64#4]
Here only the 3 first captions are visible.
Hum... a new bug in msegui?
OK, I will investigate for a new combat (or maybe you have a idea what is wrong)?

![popup_caption](https://github.com/user-attachments/assets/d01ace55-89cb-4f4a-9d47-3a2ac55c4a16)

**Comment by fredvs** [comment]
Ha, ok, I see, you did not assign yet all the captions, because if I comment those lines the caption from Object Inspector tpopupmenu1 appears.

So, nice, it is not a bug in msegui.
Maybe the caption str could be assigned or, if not now, only comment this code?

```
{
mainfo.tpopupmenu1.menu.items[3].caption := str_editevents;
mainfo.tpopupmenu1.menu.items[4].caption := str_addevent;
mainfo.tpopupmenu1.menu.items[5].caption := str_notebook;
mainfo.tpopupmenu1.menu.items[6].caption := str_addpeople;
mainfo.tpopupmenu1.menu.items[7].caption := str_addorganization;
mainfo.tpopupmenu1.menu.items[8].caption := str_help;
mainfo.tpopupmenu1.menu.items[9].caption := str_settings;mainfo.tpopupmenu1.menu.items[10].caption := str_flash;
mainfo.tpopupmenu1.menu.items[11].caption := str_yearlist;
mainfo.tpopupmenu1.menu.items[12].caption := str_clockpanel;
mainfo.tpopupmenu1.menu.items[13].caption := str_quit;
}
```

![popup_caption2](https://github.com/user-attachments/assets/f20d345b-a0ee-4ad2-ba82-5304dcbb65ec)

**Comment by fredvs** [comment]
I propose also to disable the exit dialog, imho it is a few boring.

```
procedure tmainfo.menuexit(const sender: TObject);
begin
// if askyesno('        Выйти ? | Exit ?        ', 'GORG64') then
 AppClose;
end;
```

**Comment by galaxysite** [comment]
I just started writing internationalization for GORG.
There are two ways to solve this situation: check these lines for emptiness or write your own language file for your locale. Along with ru_RU.txt and en_US.txt in lang_s. And place it in /usr/share/doc/gorg64/ when installation.

`mainfo.tpopupmenu1.menu.items[3].caption := str_editevents;`
->
`if str_editevents <> '' then mainfo.tpopupmenu1.menu.items[3].caption := str_editevents;`

**Comment by galaxysite** [comment]
> I propose also to disable the exit dialog, imho it is a few boring.

Good idea. Yes, it's faster that way.

**Comment by galaxysite** [comment]
I add and upload this checkings.

**Comment by fredvs** [comment]
Hello Alexander.
Yes, languages for GORG64 would be a big plus.
Did you read this:
https://github.com/galaxysite/gorg64/issues/1#issuecomment-2466594460
Are you ok or do you prefer the big icons?
If you are ok with the icons 32x32, I did already the scale of all your icons 64x64 to 32x32.
