### ISSUE TITLE
Error with make deb

### ISSUE THREAD

**Issue by fredvs** [galaxysite/gorg64#8]
Hello.

I try to use the makefile.
`$ make`

OK, all is compiled without any error.

`$ make deb`
The deb is created but there are those errors:

```
ar: creating ../gorg64_2.0.0-1_amd64.deb
rm -f ./debian/control.tar.xz ./debian/data.tar.xz data.tar md5sums
lintian --tag-display-limit 0 gorg64_2.0.0-1_amd64.deb
E: gorg64: control-file-has-bad-permissions postinst 0775 != 0755
E: gorg64: control-file-has-bad-permissions postrm 0775 != 0755
E: gorg64: statically-linked-binary usr/bin/gorg64_runner
E: gorg64: statically-linked-binary usr/bin/gorg64_spkoff
E: gorg64: statically-linked-binary usr/bin/gorg64_spkon
E: gorg64: statically-linked-binary usr/bin/gorg64_spkplay
E: gorg64: statically-linked-binary usr/bin/gorg64_spktone
W: gorg64: hardening-no-pie [usr/bin/gorg64]

```

Trying to install the deb file:
```

~/gorg64-main$ sudo apt install /home/fred/gorg64-main/gorg64_2.0.0-1_amd64.deb
[sudo] password for fred: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'gorg64' instead of '/home/fred/gorg64-main/gorg64_2.0.0-1_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gorg64 : Depends: elfkickers but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by fredvs** [comment]
OK I found the debian package of **elfkickers** for x86_64 and installed it.
And package GORG64 is installed ok now.

Nice!  (but needs lot of dependencies with some not "standard" :-(  )

Maybe we can discuss about a version of GORG64 OOTB that does not need any installation, all is in the sub-directory of gorg64 and so it can be used from a USB stick for example.
In the project **LazPaint**, we have 2 versions, one deb with "official" installation of deb-linux package and a other with only a zip with lazpaint executable and subdirectory of all needed.

**Comment by galaxysite** [comment]
elfkickers for this version not required but possible. I exclude this dependent in future commit. Also make correction in file rights.

lintian say about not pie executables. All maked by FPC (and self fpc executables) mainstream executables are like this. I made a special, unique version of the FPC with activated PIE.
http://soft.self-made-free.ru/fpcpie1_8.tar.xz
http://soft.self-made-free.ru/lazaruspie_4.tar.xz
Only use it can 0 error get from lintian.

But it's a hassle.

**Comment by fredvs** [comment]
>I made a special, unique version of the FPC with activated PIE.

Not sure to understand, using those fpc param **-Cg -k-pie -k-znow** does not work for you?
If no, I would be very happy, if you agree, to use your fixes for **fpc-ootb**.
https://github.com/fredvs/freepascal-ootb

(If fpc devs dont want your patch)

**Comment by fredvs** [comment]
Here compilation of GORG64 with parameter **-Cg -k-pie -k-znow** shows this:

```
$ file /home/fred/gorg64-main/src/gorg64
/home/fred/gorg64-main/src/gorg64: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.4.0, stripped

```

**Comment by galaxysite** [comment]
> -Cg -k-pie -k-znow

May be try it ?

I get correct executables only with my-patched version fpc.
May be currently version fpc improved ?

In documentation (https://wiki.freepascal.org/hardening) write:

> Small, command line applications that would generate a statically linked binary will compile fine but not run ("No such file or directory"). The difficulty is that FPC does not bother to embed instructions about portable linking in such a binary because it appears unnecessary. The solution is to add "{$linklib c}" without the inverted commas to your source. This requests LibC be linked, forcing a dynamically linked binary and FPC provides the necessary information for the linker.

And with my patch I made FPC make correct correctly working files right away without dividing into large and small. This patched version was used when fixing the Radeon bug in MSE. That's why lintian didn't give errors and everything worked.

**Comment by galaxysite** [comment]
> if you agree

I agree. :)

If this patch is compatible with fpc-ootb and needed.

**Comment by fredvs** [comment]
>May be currently version fpc improved ?

**-Cg -k-pie -k-znow** works from fpc 3.2.2 but maybe not the right way, I am not expert.

**Comment by fredvs** [comment]
Sorry to annoy you once again.

But if I try to compile last commit of GORG64 using **make** there is that error:

```
./ver
make[1]: ./ver: No such file or directory
make[1]: *** [Makefile:5: gorg64] Error 127
make[1]: Leaving directory '/home/fred/gorg64-main/src'
make: *** [Makefile:4: gorg64] Error 2

```

**Comment by fredvs** [comment]
Yep, you are totally right.

Trying to run all other compiled apps in the directory /src  gives error message and the guilty is **-Cg -k-pie -k-znow** .

I did remove all the **-Cg -k-pie -k-znow** in the  /src makefile and now **ver** and other apps can run.

The most strange is that compiling gorg64.pas with **-Cg -k-pie -k-znow**  gives a working app.

**Comment by galaxysite** [comment]
> The most strange is that compiling gorg64.pas with -Cg -k-pie -k-znow gives a working app.

It's not so bad if gorg64 compiled successfully. Let's assume that gorg64 was considered by Pascal as a large program, and the rest as small. I'll try to add the **-k-lc** key to the small ones.

**Comment by galaxysite** [comment]
And {$linklib c} in it body.

**Comment by galaxysite** [comment]
About ootb patch:
[ootbfiles.zip](https://github.com/user-attachments/files/17730927/ootbfiles.zip)

About portable version of GORG + OOTB. Yes, but as about autoload when system start ?
Everything except autoloading can be made portable.

**Comment by fredvs** [comment]
> And {$linklib c} in it body.

Wow, you are a wonderful champion!
It works now using the makefile, no more error with ver and other litle apps,, the deb is created and installing the deb is out of the box.
Congratulation.

I will deeply study your OOTB patch, many thanks.

Fre;D

**Comment by fredvs** [comment]
Hello Alexander.

About the patch of fpc-ootb, I am not sure in what directory I must copy the files.
Is the Makefile the file from root directory? 

Thanks.

**Comment by galaxysite** [comment]
> Is the Makefile the file from root directory?

Yes. From root. But it maybe exclude.

Only two files (from ./compiler/systems) are important, the third one is left for historical reasons - it only adds a key -Cg.
1. In  i_linux.pas :
added parameter tf_pic_default in system_x86_64_linux_info record.

2. In t_linux.pas changed ExeCmd and DllCmd to:
     ExeCmd[1]:='ld -lc --pie --dynamic-linker=/lib64/ld-linux-x86-64.so.2 '+platformopt+' $OPT $DYNLINK $STATIC $GCSECTIONS $STRIP $MAP -L. -o $EXE';
     DllCmd[1]:='ld -lc --pie --dynamic-linker=/lib64/ld-linux-x86-64.so.2 '+platformopt+' $OPT $INIT $FINI $SONAME $MAP -shared $GCSECTIONS -L. -o $EXE';

**Comment by fredvs** [comment]
Many thanks for the patch and the infos, I will attack that this week-end.

**Comment by fredvs** [comment]
The files you gave in zip are the same as those of fpc-ootb.
So I try to add the modifications but I have a doubt about it:

>In i_linux.pas :
>added parameter tf_pic_default in system_x86_64_linux_info record.

Is it into flags? (but it is already there)

```
flags        : [tf_smartlink_sections,tf_needs_symbol_size,
                   tf_needs_dwarf_cfi, tf_library_needs_pic,
                  tf_needs_symbol_type,tf_files_case_sensitive,
                 **tf_pic_default**,
                 tf_has_winlike_resources,tf_safecall_exceptions,
                 tf_safecall_clearstack];

```      

For  t_linux.pas, ok, modif are done.

But at compilation:

`/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/crtbegin.o:
 relocation R_X86_64_32 against hidden symbol __TMC_END__'
 can not be used when making a PIE object
/usr/bin/ld: failed to set dynamic section sizes: bad value
fpmake.pp(58,1) Error: Error while linking
fpmake.pp(58,1) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
make[2]: *** [Makefile:1731: fpmake] Error 1
make[2]: Leaving directory '/home/fred/freepascal-ootb-324/packages'
make[1]: *** [Makefile:2707: packages_smart] Error 2
make[1]: Leaving directory '/home/fred/freepascal-ootb-324'
make: *** [Makefile:2862: build-stamp.x86_64-linux] Error 2
`

**Comment by fredvs** [comment]
Hum, I did check your fpcpie1 from there https://github.com/galaxysite/gorg64/issues/8#issuecomment-2469621492 and it seems to be code from fpc 3.3.1.
But last fpc-ootb code is based on fpc 3.2.4.
Maybe there are more other things to change.
