### ISSUE TITLE
Error with last commit.

### ISSUE THREAD

**Issue by fredvs** [galaxysite/gorg64#9]
Hello.

There is a crash with last commit:

`An unhandled exception occurred at $0000000000470E8E :
ERangeError : Range check error
  $0000000000470E8E  CHANGELANG,  line 374 of main.pas
  $0000000000471DC9  ONCREATE,  line 431 of main.pas
  $00000000005B7B49  DOONCREATE,  line 1168 of ../../mseide-msegui/lib/common/widgets/mseforms.pas
  $00000000005B7ED3  READSTATE,  line 1270 of ../../mseide-msegui/lib/common/widgets/mseforms.pas
  $00000000004E4369  READROOTCOMPONENT,  line 6835 of ../../mseide-msegui/lib/common/fpccompatibility/mclasses.pas
  $00000000005063B0  LOADMODULE,  line 2392 of ../../mseide-msegui/lib/common/kernel/mseclasses.pas
  $0000000000507EE6  DOLOAD,  line 3091 of ../../mseide-msegui/lib/common/kernel/mseclasses.pas
  $0000000000507C7A  INITMSECOMPONENT,  line 3115 of ../../mseide-msegui/lib/common/kernel/mseclasses.pas
  $0000000000508005  LOADMSEMODULE,  line 3233 of ../../mseide-msegui/lib/common/kernel/mseclasses.pas
  $00000000005B7474  CREATE,  line 1068 of ../../mseide-msegui/lib/common/widgets/mseforms.pas
  $00000000005BADB9  CREATE,  line 2383 of ../../mseide-msegui/lib/common/widgets/mseforms.pas
  $00000000005B761E  CREATE,  line 1086 of ../../mseide-msegui/lib/common/widgets/mseforms.pas
  $0000000000506124  CREATEMODULE,  line 2344 of ../../mseide-msegui/lib/common/kernel/mseclasses.pas
  $000000000045BA72  CREATEFORM,  line 21048 of ../../mseide-msegui/lib/common/kernel/msegui.pas
  $000000000040647F  main,  line 78 of gorg64.pas
`

It comes from this:

```
procedure tmainfo.ChangeLang;
var f : Int64;
begin
lang := locales_s[tun.p^.lang_numb]; // here
```

It is because on my system, this:
`writeln(tun.p^.lang_numb);`
Gives **247** who is > **MAX_LANGS**

A temporary workaround is that:

```
if tun.p^.lang_numb <= MAX_LANGS then 
lang := locales_s[tun.p^.lang_numb];
```

**Comment by galaxysite** [comment]
I add property with checking MAX_LANGS.

**Comment by fredvs** [comment]
Thanks, it work now ;)
